main_directory = "bottleneck-sim/"

random_seed = 123454321

[grid_network]
nb_rows = 1
nb_columns = 2
length = 1000
right_to_left = false

[road_network]
default_speed_limit = 120
capacities = 16_000

[node_od_matrix]
each = 10_000

[mode_choice]
modes = ["car_driver"]
# Uncomment to add the outside option alternative.
#modes = ["car_driver", "outside_option"]
#model = "Logit"
#mu = 1

[modes]
[modes.car_driver]
alpha = 10

# Uncomment to add the outside option alternative.
#[modes.outside_option]
#constant = -5

[departure_time_choice]
model = "ContinuousLogit"
mu = 1

[departure_time.linear_schedule]
beta = 5
gamma = 7
# Constant tstar over agents.
tstar = 07:30:00
# Normally distributed tstar over agents.
#tstar = { mean = 07:30:00, std = 600, distribution = "Normal" }

[simulation]
period = [07:00:00, 08:00:00]
recording_interval = 60
learning_factor = 0.1
nb_iterations = 200

[metropolis_core]
exec_path = "execs/metropolis_cli"
