main_directory = "bottleneck-sim/"

random_seed = 13081996

[grid_network]
nb_rows = 1
nb_columns = 2
length = 1000
right_to_left = false

[road_network]
default_speed_limit = 120
capacities = 16_000

[node_od_matrix]
each = 10_000

[mode_choice]
modes = ["car_driver"]
# model = "Logit"
# mu = 1.0

[modes]
[modes.car_driver]
alpha = 10.0

# [modes.outside_option]
# constant = -5.0

[departure_time_choice]
model = "ContinuousLogit"
mu = 1.0

[departure_time.linear_schedule]
beta = 5.0
gamma = 7.0
tstar = 07:30:00

[simulation]
period = [07:00:00, 08:00:00]
recording_interval = 60
learning_factor = 0.1
nb_iterations = 200

[metropolis_core]
exec_path = "execs/metropolis_cli"
