# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "metro-pipeline"
version = "0.1.0"
description = "TODO"
requires-python = ">=3.12"
authors = [{ name = "Lucas Javaudin", email = "lucas@lucasjavaudin.com" }]
dependencies = [
    "geopandas>=1.1.1",
    "loguru>=0.7.3",
    "metro-common",
    "numpy>=2.3.4",
    "polars>=1.35.1",
    "termcolor>=3.2.0",
    "toml>=0.10.2",
    "typeguard>=4.4.4",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.14.3",
]
