# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "metro-common"
version = "0.1.0"
description = "TODO"
requires-python = ">=3.12"
authors = [{ name = "Lucas Javaudin", email = "lucas@lucasjavaudin.com" }]
dependencies = [
    "geopandas>=1.1.1",
    "isodate>=0.7.2",
    "loguru>=0.7.3",
    "polars>=1.35.1",
    "pyarrow>=22.0.0",
    "pyogrio>=0.11.1",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.14.3",
]
