# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "metro-spatial"
version = "0.1.0"
description = "TODO"
requires-python = ">=3.12"
authors = [{ name = "Lucas Javaudin", email = "lucas@lucasjavaudin.com" }]
dependencies = [
    "metro-common",
    "metro-pipeline",
    "geopandas>=1.1.1",
    "osmium>=4.2.0",
    "pyproj>=3.7.2",
    "shapely>=2.1.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.3",
]
